name: proyecto_albert_garrido
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  provider: ^6.0.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # 1️⃣ Añade flutter_launcher_icons aquí:
  flutter_launcher_icons: ^0.10.0

# 2️⃣ Configuración de launcher icons y nombre de app:
flutter_icons:
  android: true         # genera iconos en mipmap-*
  ios: true             # genera icons en Assets.xcassets
  image_path: "assets/icon/app_icon.png"
  android_name: "MiApp" # display name en Android
  ios_name: "MiApp"     # display name en iOS

flutter:
  uses-material-design: true

  # 3️⃣ Asegúrate de incluir la carpeta de tu icono en assets:
  assets:
    - assets/icon/app_icon.png
